FROM node:20-alpine AS dev
WORKDIR /app/webui
COPY webui/package*.json ./
RUN npm ci
COPY webui ./
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]

FROM node:20-alpine AS build
WORKDIR /app/webui
COPY webui/package*.json ./
RUN npm ci
COPY webui ./
RUN npm run build

FROM nginx:1.27-alpine AS prd
COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/webui/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
