FROM node:20-alpine AS build

WORKDIR /app/webui
COPY webui/package*.json ./
RUN npm ci
COPY webui ./
RUN npm run build

FROM node:20-alpine

WORKDIR /app/webui
COPY --from=build /app/webui ./
EXPOSE 3000

CMD ["node", "scripts/start-next.mjs", "start"]
