FROM python:3.14-slim AS base

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY zstar ./zstar
COPY config.yaml ./config.yaml

FROM base AS dev
CMD ["uvicorn", "zstar.api.start_backend:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

FROM base AS prd
CMD ["uvicorn", "zstar.api.start_backend:app", "--host", "0.0.0.0", "--port", "8000"]
